name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PY_COLORS: "1"
  COLUMNS: 120

jobs:
  linux-build:
    name: Linux, Python ${{matrix.python_version}}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python_version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python_version}}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build
        run: python -m pip wheel .

      - name: Test
        run: |
          python -m pip install --no-index --find-links=. complate_cpp_for_python
          python -m pytest -v


  macos-build:
    name: macOS, Python ${{matrix.python_version}}
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        python_version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python_version}}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build
        run: python -m pip wheel .

      - name: Test
        run: |
          python -m pip install --no-index --find-links=. complate_cpp_for_python
          python -m pytest -v
