name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    uses: tmehnert/complate-cpp-for-python/.github/workflows/build.yml@main


  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-20.04
    needs: [ build ]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


  github-release:
    name: Github Release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/*
